//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPersonas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PersonasContext : DbContext
    {
        public PersonasContext()
            : base("name=PersonasContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<pais> pais { get; set; }
        public virtual DbSet<persona> persona { get; set; }
    
        public virtual int Actualizar_Persona(Nullable<int> id, string nombres, string apellidos, Nullable<System.DateTime> fechaNacim, Nullable<System.DateTime> fechaFallec, Nullable<int> paisNacim)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nombresParameter = nombres != null ?
                new ObjectParameter("nombres", nombres) :
                new ObjectParameter("nombres", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("apellidos", apellidos) :
                new ObjectParameter("apellidos", typeof(string));
    
            var fechaNacimParameter = fechaNacim.HasValue ?
                new ObjectParameter("fechaNacim", fechaNacim) :
                new ObjectParameter("fechaNacim", typeof(System.DateTime));
    
            var fechaFallecParameter = fechaFallec.HasValue ?
                new ObjectParameter("fechaFallec", fechaFallec) :
                new ObjectParameter("fechaFallec", typeof(System.DateTime));
    
            var paisNacimParameter = paisNacim.HasValue ?
                new ObjectParameter("paisNacim", paisNacim) :
                new ObjectParameter("paisNacim", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Actualizar_Persona", idParameter, nombresParameter, apellidosParameter, fechaNacimParameter, fechaFallecParameter, paisNacimParameter);
        }
    
        public virtual int Eliminar_Persona(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Persona", idParameter);
        }
    
        public virtual ObjectResult<Informe_Nac_Fallec_Result> Informe_Nac_Fallec()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Informe_Nac_Fallec_Result>("Informe_Nac_Fallec");
        }
    }
}
